sudo: true

language: php
php:
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3

before_script:
  - composer update --no-interaction

script:
  - mkdir -p log
  - ./vendor/bin/phpunit -c tests/phpunit.xml --coverage-clover log/clover.xml tests

after_script:
  - php ./vendor/bin/coveralls -v
