services:

  sokil.command_bus.default:
    class: Sokil\CommandBusBundle\CommandBus
    arguments:
      - "@sokil.command_bus.command_handler_service_resolver"
    tags:
      - {name: sokil.command_bus}

  sokil.command_bus:
    alias: sokil.command_bus.default

  sokil.command_bus.command_handler_service_resolver:
    class: Sokil\CommandBusBundle\CommandBus\CommandHandlerServiceResolver
    calls:
      - [setContainer, ["@service_container"]]
